# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "System Engineering 101 Help Center"
email: jiangzijian77@gmail.com
description: "System engineering problems quick solved."
baseurl: "/system-engineering-101"
url: "https://callmenezha.github.io/"
twitter_username: ""
github_username:  "CallmeNezha"
color_theme:  "#0081ff"
color_text:  "#fff"
language:  "zh"

# Build settings
markdown: kramdown
permalink: /:title/
gems: [jekyll-paginate]
paginate: 10

# Plugins
plugins_dir:
  - jekyll-admin
